params:
  seed: 7

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 128]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  config:
    name: cartpole_jym
    full_experiment_name: cartpole_jym
    env_name: jym
    multi_gpu: False
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    normalize_advantage: True
    use_smooth_clamp: False
    reward_shaper:
      scale_value: 1.0
    gamma: 0.8
    tau: 0.9
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 2048
    max_epochs: 40
    save_best_after: 100
    save_frequency: 25
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    num_actors: 1024
    minibatch_size: 1024
    mini_epochs: 6
    critic_coef: 2
    device: 'cuda'

    clip_value: True
    bound_loss_type: regularisation
    bounds_loss_coef: 0.08

    env_config:
      env_name: cartpole
